### ISSUE TITLE
The lower WiFi is blocked by the lower toolbox

### ISSUE THREAD

**Issue by OlegXio** [LowSkillDeveloper/3WiFiLocator-Unofficial#24]
Screenshot_20240601-092747.jpg](https://github.com/LowSkillDeveloper/3WiFiLocator-Unofficial/assets/125251033/234275a5-7ad7-4ae7-b6fd-9ed14eb3e17b)

**Comment by LowSkillDeveloper** [comment]
Fixed in version 2.1 (but now there will be no cutout)
